server:
  port: 8191
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bijaykoirala123/microservice-configuration
          search-paths:
           - '*service'



